import {
  AppRole,
  AppUser,
  DashboardPageData,
  Location,
  NavItem,
  Site,
  StockTakePlan,
  Warehouse,
} from "@/lib/types";

export const appNavigation: NavItem[] = [
  { title: "Admin", href: "/admin", icon: "AD", roles: ["system-admin"] },
  { title: "Auditor", href: "/auditor", icon: "AU", roles: ["auditor"] },
  { title: "Warehouse", href: "/warehouse", icon: "WH", roles: ["warehouse-user"] },
  { title: "Analytics", href: "/analytics", icon: "AN", roles: ["system-admin", "auditor", "management"], badge: "BI" },
  { title: "Management", href: "/management-dashboard", icon: "MG", roles: ["management", "system-admin"] },
  { title: "Users", href: "/users", icon: "US", roles: ["system-admin"] },
  { title: "Stock Take", href: "/stocktake/plans", icon: "PL", roles: ["system-admin", "auditor"] },
  { title: "Calendar", href: "/stocktake/calendar", icon: "CL", roles: ["system-admin", "auditor"] },
  { title: "My Plans", href: "/stocktake/my-plans", icon: "CT", roles: ["warehouse-user", "auditor"], badge: "Live" },
  { title: "Sync Status", href: "/sync-status", icon: "SY", roles: ["system-admin", "auditor", "warehouse-user"], badge: "Live" },
  { title: "Conflicts", href: "/conflicts", icon: "CF", roles: ["system-admin", "auditor"], badge: "Review" },
  { title: "Anomalies", href: "/anomalies", icon: "AX", roles: ["system-admin", "auditor", "management"], badge: "Risk" },
  { title: "Reports", href: "/reports", icon: "RP", roles: ["system-admin", "auditor", "management"], badge: "Live" },
  { title: "Settings", href: "/settings", icon: "ST", roles: ["system-admin"] },
];

export const usersByRole: Record<
  AppRole,
  { name: string; title: string; role: AppRole; location: string; initials: string }
> = {
  "system-admin": {
    name: "Harshil Patel",
    title: "Regional Operations Lead",
    role: "system-admin",
    location: "Ahmedabad DC",
    initials: "HP",
  },
  auditor: {
    name: "Meera Shah",
    title: "Internal Audit Manager",
    role: "auditor",
    location: "Surat DC",
    initials: "MS",
  },
  "warehouse-user": {
    name: "Jignesh Parmar",
    title: "Warehouse Shift Supervisor",
    role: "warehouse-user",
    location: "Ahmedabad DC",
    initials: "JP",
  },
  management: {
    name: "Nirav Desai",
    title: "Operations Director",
    role: "management",
    location: "Corporate Office",
    initials: "ND",
  },
};

export function resolveRoleFromPathname(pathname: string): AppRole {
  if (pathname.startsWith("/auditor")) return "auditor";
  if (
    pathname.startsWith("/warehouse") ||
    pathname.startsWith("/counting") ||
    pathname.startsWith("/stocktake/my-plans") ||
    pathname.startsWith("/stocktake/count")
  ) {
    return "warehouse-user";
  }
  if (pathname.startsWith("/analytics")) return "system-admin";
  if (pathname.startsWith("/management-dashboard")) return "management";
  if (pathname.startsWith("/anomalies")) return "auditor";
  if (pathname.startsWith("/stocktake")) return pathname.includes("calendar") ? "auditor" : "system-admin";
  if (pathname.startsWith("/management") || pathname.startsWith("/reports")) return "management";
  return "system-admin";
}

export const warehouses: Warehouse[] = [
  {
    id: "wh-ahd",
    name: "Ahmedabad Distribution Center",
    code: "AHD-DC",
    city: "Ahmedabad",
    region: "Gujarat Central",
    status: "active",
  },
  {
    id: "wh-srt",
    name: "Surat Distribution Center",
    code: "SRT-DC",
    city: "Surat",
    region: "South Gujarat",
    status: "active",
  },
  {
    id: "wh-rjt",
    name: "Rajkot Satellite Warehouse",
    code: "RJT-SW",
    city: "Rajkot",
    region: "Saurashtra",
    status: "active",
  },
];

export const sites: Site[] = [
  {
    id: "site-ahd-a1",
    warehouseId: "wh-ahd",
    name: "Aisle A Storage",
    code: "A1",
    type: "Primary Storage",
    manager: "Jignesh Parmar",
  },
  {
    id: "site-ahd-d3",
    warehouseId: "wh-ahd",
    name: "Dispatch Rack D3",
    code: "D3",
    type: "Dispatch",
    manager: "Krunal Soni",
  },
  {
    id: "site-ahd-frz",
    warehouseId: "wh-ahd",
    name: "Frozen Bay",
    code: "FRZ",
    type: "Cold Chain",
    manager: "Priya Chauhan",
  },
  {
    id: "site-srt-b1",
    warehouseId: "wh-srt",
    name: "Bulk Pallet Zone",
    code: "B1",
    type: "Bulk",
    manager: "Meera Shah",
  },
  {
    id: "site-srt-c2",
    warehouseId: "wh-srt",
    name: "Cosmetics Rack C2",
    code: "C2",
    type: "High Value",
    manager: "Nirali Dave",
  },
  {
    id: "site-rjt-a2",
    warehouseId: "wh-rjt",
    name: "Main Picking A2",
    code: "A2",
    type: "Picking",
    manager: "Rina Desai",
  },
  {
    id: "site-rjt-r1",
    warehouseId: "wh-rjt",
    name: "Reserve Rack R1",
    code: "R1",
    type: "Reserve Storage",
    manager: "Rina Desai",
  },
];

export const locations: Location[] = [
  {
    id: "loc-ahd-a1-01",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-a1",
    name: "Aisle A1 Bay 01",
    code: "A1-01",
    aisle: "A1",
    zone: "Storage",
    barcode: "LOC-A1-01",
    status: "active",
  },
  {
    id: "loc-ahd-a1-02",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-a1",
    name: "Aisle A1 Bay 02",
    code: "A1-02",
    aisle: "A1",
    zone: "Storage",
    barcode: "LOC-A1-02",
    status: "active",
  },
  {
    id: "loc-ahd-a1-04",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-a1",
    name: "Aisle A1 Bay 04",
    code: "A1-04",
    aisle: "A1",
    zone: "Storage",
    barcode: "LOC-A1-04",
    status: "active",
  },
  {
    id: "loc-ahd-d3-01",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-d3",
    name: "Dispatch D3 Rack 01",
    code: "D3-01",
    aisle: "D3",
    zone: "Dispatch",
    barcode: "LOC-D3-01",
    status: "active",
  },
  {
    id: "loc-ahd-d3-02",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-d3",
    name: "Dispatch D3 Rack 02",
    code: "D3-02",
    aisle: "D3",
    zone: "Dispatch",
    barcode: "LOC-D3-02",
    status: "active",
  },
  {
    id: "loc-ahd-frz-01",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-frz",
    name: "Frozen Bay 01",
    code: "FRZ-01",
    aisle: "FRZ",
    zone: "Cold Chain",
    barcode: "LOC-FRZ-01",
    status: "active",
  },
  {
    id: "loc-ahd-frz-02",
    warehouseId: "wh-ahd",
    siteId: "site-ahd-frz",
    name: "Frozen Bay 02",
    code: "FRZ-02",
    aisle: "FRZ",
    zone: "Cold Chain",
    barcode: "LOC-FRZ-02",
    status: "active",
  },
  {
    id: "loc-srt-b1-01",
    warehouseId: "wh-srt",
    siteId: "site-srt-b1",
    name: "Bulk B1 Pallet 01",
    code: "B1-01",
    aisle: "B1",
    zone: "Bulk",
    barcode: "LOC-B1-01",
    status: "active",
  },
  {
    id: "loc-srt-b1-02",
    warehouseId: "wh-srt",
    siteId: "site-srt-b1",
    name: "Bulk B1 Pallet 02",
    code: "B1-02",
    aisle: "B1",
    zone: "Bulk",
    barcode: "LOC-B1-02",
    status: "active",
  },
  {
    id: "loc-srt-c2-01",
    warehouseId: "wh-srt",
    siteId: "site-srt-c2",
    name: "Cosmetics C2 Shelf 01",
    code: "C2-01",
    aisle: "C2",
    zone: "High Value",
    barcode: "LOC-C2-01",
    status: "active",
  },
  {
    id: "loc-srt-c2-03",
    warehouseId: "wh-srt",
    siteId: "site-srt-c2",
    name: "Cosmetics C2 Shelf 03",
    code: "C2-03",
    aisle: "C2",
    zone: "High Value",
    barcode: "LOC-C2-03",
    status: "active",
  },
  {
    id: "loc-rjt-a2-01",
    warehouseId: "wh-rjt",
    siteId: "site-rjt-a2",
    name: "Picking A2 Bay 01",
    code: "A2-01",
    aisle: "A2",
    zone: "Picking",
    barcode: "LOC-A2-01",
    status: "active",
  },
  {
    id: "loc-rjt-a2-02",
    warehouseId: "wh-rjt",
    siteId: "site-rjt-a2",
    name: "Picking A2 Bay 02",
    code: "A2-02",
    aisle: "A2",
    zone: "Picking",
    barcode: "LOC-A2-02",
    status: "active",
  },
  {
    id: "loc-rjt-r1-01",
    warehouseId: "wh-rjt",
    siteId: "site-rjt-r1",
    name: "Reserve R1 Bin 01",
    code: "R1-01",
    aisle: "R1",
    zone: "Reserve",
    barcode: "LOC-R1-01",
    status: "active",
  },
];

export const businessUsers: AppUser[] = [
  {
    id: "usr-001",
    employeeCode: "EMP-1001",
    name: "Harshil Patel",
    email: "harshil.patel@ashabhai.co",
    phone: "+91 98765 41001",
    role: "Admin",
    warehouseId: "wh-ahd",
    siteIds: ["site-ahd-a1", "site-ahd-d3"],
    locationIds: ["loc-ahd-a1-01", "loc-ahd-d3-01"],
    status: "active",
  },
  {
    id: "usr-002",
    employeeCode: "EMP-2014",
    name: "Meera Shah",
    email: "meera.shah@ashabhai.co",
    phone: "+91 98765 41014",
    role: "Auditor",
    warehouseId: "wh-srt",
    siteIds: ["site-srt-b1", "site-srt-c2"],
    locationIds: ["loc-srt-b1-01", "loc-srt-c2-01"],
    status: "active",
  },
  {
    id: "usr-003",
    employeeCode: "EMP-3048",
    name: "Jignesh Parmar",
    email: "jignesh.parmar@ashabhai.co",
    phone: "+91 98765 43048",
    role: "Warehouse",
    warehouseId: "wh-ahd",
    siteIds: ["site-ahd-a1"],
    locationIds: ["loc-ahd-a1-01", "loc-ahd-a1-02", "loc-ahd-a1-04"],
    status: "active",
  },
  {
    id: "usr-004",
    employeeCode: "EMP-3052",
    name: "Krunal Soni",
    email: "krunal.soni@ashabhai.co",
    phone: "+91 98765 43052",
    role: "Warehouse",
    warehouseId: "wh-ahd",
    siteIds: ["site-ahd-d3", "site-ahd-frz"],
    locationIds: ["loc-ahd-d3-02", "loc-ahd-frz-01"],
    status: "inactive",
  },
  {
    id: "usr-005",
    employeeCode: "EMP-2021",
    name: "Rina Desai",
    email: "rina.desai@ashabhai.co",
    phone: "+91 98765 42021",
    role: "Auditor",
    warehouseId: "wh-rjt",
    siteIds: ["site-rjt-a2", "site-rjt-r1"],
    locationIds: ["loc-rjt-a2-01", "loc-rjt-r1-01"],
    status: "active",
  },
  {
    id: "usr-006",
    employeeCode: "EMP-3059",
    name: "Priya Chauhan",
    email: "priya.chauhan@ashabhai.co",
    phone: "+91 98765 43059",
    role: "Warehouse",
    warehouseId: "wh-ahd",
    siteIds: ["site-ahd-frz"],
    locationIds: ["loc-ahd-frz-01", "loc-ahd-frz-02"],
    status: "active",
  },
  {
    id: "usr-007",
    employeeCode: "EMP-3064",
    name: "Nirali Dave",
    email: "nirali.dave@ashabhai.co",
    phone: "+91 98765 43064",
    role: "Warehouse",
    warehouseId: "wh-srt",
    siteIds: ["site-srt-c2"],
    locationIds: ["loc-srt-c2-01", "loc-srt-c2-03"],
    status: "active",
  },
];

export const stockTakePlans: StockTakePlan[] = [
  {
    id: "plan-001",
    code: "FY26-AHD-ANNUAL",
    name: "FY26 Ahmedabad Annual Stock Take",
    description: "Annual blind count covering primary storage, dispatch and frozen inventory.",
    warehouseId: "wh-ahd",
    siteIds: ["site-ahd-a1", "site-ahd-d3", "site-ahd-frz"],
    locationIds: [
      "loc-ahd-a1-01",
      "loc-ahd-a1-02",
      "loc-ahd-a1-04",
      "loc-ahd-d3-01",
      "loc-ahd-d3-02",
      "loc-ahd-frz-01",
    ],
    scheduledDate: "2026-04-18",
    scheduleWindow: "14:00 - 22:00",
    firstCountUserId: "usr-003",
    secondCountUserId: "usr-002",
    notes: "Blind count enabled. Route mixed pallets and damaged stock for supervisor review.",
    instructions: "Scan location first, then item. Use exception path for mixed pallets and damaged units.",
    countMethod: "Blind Count",
    locked: true,
    highVariancePlaceholder: true,
    status: "Scheduled",
  },
  {
    id: "plan-002",
    code: "APR26-SRT-CYCLE",
    name: "April Surat Cycle Count",
    description: "Cycle count for bulk and cosmetics sections ahead of month-close reconciliation.",
    warehouseId: "wh-srt",
    siteIds: ["site-srt-b1", "site-srt-c2"],
    locationIds: ["loc-srt-b1-01", "loc-srt-b1-02", "loc-srt-c2-01"],
    scheduledDate: "2026-04-21",
    scheduleWindow: "09:30 - 16:30",
    firstCountUserId: "usr-007",
    secondCountUserId: "usr-002",
    notes: "Focus on high-value and bulk pallet exceptions before month close.",
    instructions: "Verify seal condition for cosmetics and isolate blocked stock before final save.",
    countMethod: "Cycle Count",
    locked: false,
    highVariancePlaceholder: false,
    status: "Draft",
  },
  {
    id: "plan-003",
    code: "APR26-RJT-SAMPLE",
    name: "Rajkot Audit Sample Count",
    description: "Audit-led sample count of picking and reserve storage for process assurance.",
    warehouseId: "wh-rjt",
    siteIds: ["site-rjt-a2", "site-rjt-r1"],
    locationIds: ["loc-rjt-a2-01", "loc-rjt-a2-02", "loc-rjt-r1-01"],
    scheduledDate: "2026-04-19",
    scheduleWindow: "11:00 - 18:00",
    firstCountUserId: "usr-005",
    secondCountUserId: "usr-003",
    notes: "Sample count for process assurance and audit validation.",
    instructions: "Supervise reserve stock access and maintain second-count segregation.",
    countMethod: "Frozen Count",
    locked: false,
    highVariancePlaceholder: true,
    status: "In Progress",
  },
];

export const dashboards: Record<AppRole, DashboardPageData> = {
  "system-admin": {
    title: "System Control Center",
    description: "Enterprise visibility across user access, integration health and active operational programs.",
    role: "system-admin",
    metrics: [
      { id: "users", label: "Active users", value: "184", helper: "Cross-role users active this week", delta: "+12%", tone: "primary" },
      { id: "health", label: "Locations scheduled", value: "147", helper: "Locations already loaded into active plans", delta: "+18", tone: "success" },
      { id: "plans", label: "First counts pending", value: "08", helper: "Plans waiting for first-count execution", delta: "+2", tone: "primary" },
      { id: "exceptions", label: "Locked plans", value: "05", helper: "Plans frozen for execution control", delta: "+1", tone: "danger" },
    ],
    trend: [
      { name: "Mon", progress: 68, variance: 1.2 },
      { name: "Tue", progress: 82, variance: 1.1 },
      { name: "Wed", progress: 76, variance: 0.9 },
      { name: "Thu", progress: 91, variance: 1.5 },
      { name: "Fri", progress: 86, variance: 1.3 },
    ],
    tasks: [
      { id: "1", title: "ERP connector credential refresh", subtitle: "Token expiry window closes in 38 minutes", meta: "Integration", tone: "danger" },
      { id: "2", title: "Warehouse tablet refresh batch", subtitle: "4 devices need fresh master data before evening shift", meta: "Devices", tone: "warning" },
      { id: "3", title: "Role segregation review", subtitle: "Dual-approval path pending governance sign-off", meta: "Security", tone: "default" },
    ],
    alerts: [
      { id: "4", title: "Usage peak detected", subtitle: "Ahmedabad DC exceeded forecast handheld session load", meta: "Performance", tone: "success" },
      { id: "5", title: "Dormant account audit", subtitle: "Two admin accounts inactive for more than 60 days", meta: "Access", tone: "warning" },
    ],
  },
  auditor: {
    title: "Audit Operations Center",
    description: "Focused supervision of plans, variance signals and bottlenecks during stock take execution.",
    role: "auditor",
    metrics: [
      { id: "plans", label: "Sites scheduled", value: "11", helper: "Audit-covered sites across live plans", delta: "+2", tone: "primary" },
      { id: "variance", label: "High variance flags", value: "04", helper: "Plans carrying risk placeholders", delta: "+1", tone: "danger" },
      { id: "coverage", label: "Second counts pending", value: "06", helper: "Awaiting independent verification counts", delta: "+2", tone: "success" },
      { id: "bottlenecks", label: "Bottleneck locations", value: "09", helper: "Slow-moving locations impacting completion", delta: "-1", tone: "warning" },
    ],
    trend: [
      { name: "AHD", progress: 82, variance: 1.8 },
      { name: "SRT", progress: 69, variance: 3.1 },
      { name: "RJT", progress: 91, variance: 0.7 },
      { name: "CLD", progress: 54, variance: 4.4 },
    ],
    tasks: [
      { id: "1", title: "Blind count verification | Ahmedabad DC", subtitle: "Aisles A1-A8 with three recount triggers", meta: "14:30 - 16:00", tone: "danger" },
      { id: "2", title: "Sample review | Rajkot site", subtitle: "Bulk pallet zone observer window confirmed", meta: "15:00 - 16:45", tone: "default" },
      { id: "3", title: "Variance sign-off | Surat DC", subtitle: "Finance observer pending", meta: "17:15 - 18:00", tone: "warning" },
    ],
    alerts: [
      { id: "4", title: "High-value SKU mismatch", subtitle: "Luxury cosmetics exceed variance limit", meta: "Escalation", tone: "danger" },
      { id: "5", title: "Cold chain plan at risk", subtitle: "Recount timing may miss dispatch cut-off", meta: "Timing", tone: "warning" },
    ],
  },
  "warehouse-user": {
    title: "Warehouse Shift Board",
    description: "Task-oriented surface for tablet crews, supervisors and shift leaders on the warehouse floor.",
    role: "warehouse-user",
    metrics: [
      { id: "assigned", label: "Assigned plans", value: "03", helper: "Active during this shift", delta: "Current", tone: "primary" },
      { id: "pending", label: "Pending locations", value: "42", helper: "Location-level count scope left in current plans", delta: "-8", tone: "warning" },
      { id: "lines", label: "Recent count lines", value: "486", helper: "Latest handheld captures stable", delta: "+94", tone: "success" },
      { id: "blocked", label: "Blocked exceptions", value: "06", helper: "Need supervisor action or review", delta: "+2", tone: "danger" },
    ],
    trend: [
      { name: "A1", progress: 72, variance: 1.4 },
      { name: "A2", progress: 61, variance: 1.1 },
      { name: "B1", progress: 84, variance: 0.8 },
      { name: "D3", progress: 48, variance: 2.6 },
    ],
    tasks: [
      { id: "1", title: "Aisle A1-A8 blind count", subtitle: "18 locations open with supervisor coverage", meta: "Ready", tone: "default" },
      { id: "2", title: "Rack D recount", subtitle: "Auditor requested recount for 4 exception bins", meta: "Blocked", tone: "danger" },
      { id: "3", title: "Fast-moving SKU cycle check", subtitle: "Cold room dispatch zone before 16:30", meta: "Today", tone: "warning" },
    ],
    alerts: [
      { id: "4", title: "Queue active on tablet 04", subtitle: "22 lines stored locally", meta: "Offline queue", tone: "warning" },
      { id: "5", title: "Supervisor note issued", subtitle: "Mixed pallets in A1 require exception routing", meta: "Floor note", tone: "success" },
    ],
  },
  management: {
    title: "Executive Operations Board",
    description: "Reserved management view with completion, risk and variance rollups across the network.",
    role: "management",
    metrics: [
      { id: "completion", label: "Network completion", value: "78%", helper: "Weighted by line count and criticality", delta: "+4.8%", tone: "primary" },
      { id: "variance", label: "Open variance value", value: "INR 18.4L", helper: "Awaiting closure or approval", delta: "-6%", tone: "danger" },
      { id: "delays", label: "Delayed plans", value: "04", helper: "Need intervention or staffing support", delta: "+1", tone: "warning" },
      { id: "performance", label: "Warehouse performance", value: "91%", helper: "SLA adherence across seven days", delta: "+2.1%", tone: "success" },
    ],
    trend: [
      { name: "AHD", progress: 82, variance: 1.8 },
      { name: "SRT", progress: 69, variance: 3.1 },
      { name: "RJT", progress: 91, variance: 0.7 },
      { name: "CLD", progress: 54, variance: 4.4 },
    ],
    tasks: [
      { id: "1", title: "Board summary placeholder", subtitle: "Phase 1 delivers shell and dashboard foundation only", meta: "Planned", tone: "default" },
    ],
    alerts: [
      { id: "2", title: "Management insights module", subtitle: "Detailed reconciliation and issue matrix reserved for next phases", meta: "Roadmap", tone: "warning" },
    ],
  },
};
